package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/yottadynamics/yottacode/internal/worktree"
)

// EnterWorktreeTool is the high-level "agent wants to work on this in
// isolation" entry point. It creates (or attaches to) a yottacode-
// managed worktree under <repo>/.yottacode/worktrees/<name>/ on
// branch worktree-<name>, copies the gitignored files listed in
// .worktreeinclude, and returns the new working directory.
//
// v1 caveat: the session's cwd does NOT swap in-process. The agent
// is told the absolute path and is expected to use absolute paths
// (or `cd <path>` via run_bash) for subsequent operations. A
// fresh session in the worktree can be started with
// `yottacode --worktree <name>` (or via the worktree CLI subcommand),
// which sets cwd at process start. In-session cwd swap is v1.1 polish.
//
// Always requires approval (auto-mode safety floor) because creating
// a worktree is a real side effect and the cwd-shift surprise
// warrants an explicit user click.
type EnterWorktreeTool struct {
	Cwd *CwdRef
}

func (t *EnterWorktreeTool) Name() string { return "enter_worktree" }

func (t *EnterWorktreeTool) Description() string {
	return "PREFERRED tool for 'create a worktree' / 'work on this in isolation' " +
		"requests. Creates (or attaches to) a yottacode-managed git worktree at " +
		"<repo>/.yottacode/worktrees/<name>/ on branch worktree-<name>, copies " +
		".worktreeinclude files (so .env etc. travel with the session), and " +
		"swaps the session's working directory to the new worktree — subsequent " +
		"read/write/edit calls with relative paths resolve inside it automatically. " +
		"Args: name (optional — auto-generated like 'bright-running-fox' if " +
		"omitted; do NOT pass a path here, just the bare name) and base " +
		"(\"fresh\" branches from origin/HEAD by default, \"head\" branches " +
		"from local HEAD to carry unpushed work). Use this instead of " +
		"git_worktree_add unless you specifically need to place a worktree at " +
		"a custom path outside the .yottacode/worktrees/ convention."
}

func (t *EnterWorktreeTool) Schema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"name": map[string]any{
				"type":        "string",
				"description": "Worktree name. Auto-generated like 'bright-running-fox' if omitted. ASCII letters, digits, hyphen, underscore; 1..64 chars; not starting with '.' or '-'.",
			},
			"base": map[string]any{
				"type":        "string",
				"enum":        []string{"fresh", "head"},
				"description": "'fresh' branches from origin/HEAD (default; no local junk). 'head' branches from local HEAD so unpushed work follows.",
			},
		},
	}
}

func (t *EnterWorktreeTool) RequiresApproval(string) bool { return true }

func (t *EnterWorktreeTool) PreviewCall(argsJSON string) string {
	var a struct {
		Name string `json:"name"`
		Base string `json:"base"`
	}
	_ = json.Unmarshal([]byte(argsJSON), &a)
	name := a.Name
	if name == "" {
		name = "<auto-generated>"
	}
	if a.Base == "" {
		a.Base = "fresh"
	}
	return fmt.Sprintf("enter_worktree(name=%s, base=%s)", name, a.Base)
}

func (t *EnterWorktreeTool) Execute(ctx context.Context, argsJSON string) (string, error) {
	var a struct {
		Name string `json:"name"`
		Base string `json:"base"`
	}
	if err := json.Unmarshal([]byte(argsJSON), &a); err != nil {
		return "", fmt.Errorf("enter_worktree: invalid args: %w", err)
	}
	if a.Base == "" {
		a.Base = "fresh"
	}
	if a.Base != "fresh" && a.Base != "head" {
		return "", fmt.Errorf("enter_worktree: base must be 'fresh' or 'head', got %q", a.Base)
	}

	repoRoot, err := worktree.ResolveRepoRoot(ctx, t.Cwd.Get())
	if err != nil {
		return "", fmt.Errorf("enter_worktree: %w", err)
	}

	name := a.Name
	if name == "" {
		name, err = worktree.Generate(ctx, repoRoot)
		if err != nil {
			return "", fmt.Errorf("enter_worktree: generate name: %w", err)
		}
	} else if err := worktree.ValidateName(name); err != nil {
		return "", err
	}

	wtDir := worktree.Dir(repoRoot, name)
	branch := worktree.Branch(name)

	// If a worktree with this path already exists, attach to it
	// instead of erroring. The agent calling enter_worktree with a
	// name it used previously is treated as "I want to keep going".
	infos, err := worktree.List(ctx, repoRoot)
	if err != nil {
		return "", fmt.Errorf("enter_worktree: list: %w", err)
	}
	for _, w := range infos {
		if samePathBasic(w.Path, wtDir) {
			if err := worktree.CopyIncluded(repoRoot, wtDir); err != nil {
				return "", fmt.Errorf("enter_worktree: copy .worktreeinclude: %w", err)
			}
			// Refresh .origin in case it's missing (older worktree
			// created before the .origin convention existed).
			_ = worktree.WriteOrigin(worktree.SlugDir(repoRoot), repoRoot)
			if err := t.swapCwd(wtDir); err != nil {
				return "", err
			}
			return fmt.Sprintf(
				"attached to existing worktree\npath: %s\nbranch: %s\nsession cwd is now this directory; subsequent reads/writes resolve relative paths against it",
				wtDir, w.Branch,
			), nil
		}
	}

	// Resolve base ref. "fresh" → origin/HEAD if available, else local HEAD.
	// "head" → local HEAD explicitly.
	baseRef := "HEAD"
	if a.Base == "fresh" {
		if _, err := gitOutput(ctx, repoRoot, "rev-parse", "--verify", "origin/HEAD"); err == nil {
			baseRef = "origin/HEAD"
		}
	}

	args := []string{"worktree", "add", "-b", branch, wtDir, baseRef}
	if _, err := gitOutput(ctx, repoRoot, args...); err != nil {
		return "", fmt.Errorf("enter_worktree: %w", err)
	}

	if err := worktree.CopyIncluded(repoRoot, wtDir); err != nil {
		// Tree exists at this point — surface the copy error but don't
		// roll back. The user can fix .worktreeinclude or copy files
		// manually; rolling back would lose the worktree creation work.
		return "", fmt.Errorf("enter_worktree: worktree created at %s but copying .worktreeinclude failed: %w", wtDir, err)
	}

	// Record the originating repo in <slug>/.origin so
	// `yottacode worktree where` can answer "which repo does this slug
	// belong to?" without needing a live worktree to query via git.
	// Soft-fail: the worktree is already usable; an .origin write
	// failure (e.g. permission denied on the slug dir) is logged as
	// part of the result text rather than rolling back.
	originNote := ""
	if err := worktree.WriteOrigin(worktree.SlugDir(repoRoot), repoRoot); err != nil {
		originNote = fmt.Sprintf("\nnote: could not record .origin (%v) — `yottacode worktree where` won't resolve this slug", err)
	}

	if err := t.swapCwd(wtDir); err != nil {
		return "", err
	}

	return fmt.Sprintf(
		"created worktree\npath: %s\nbranch: %s (from %s)\nsession cwd is now this directory; subsequent reads/writes resolve relative paths against it%s",
		wtDir, branch, baseRef, originNote,
	), nil
}

// swapCwd updates the shared CwdRef and the process's working dir
// so subsequent tool calls (including run_bash with no explicit Dir)
// operate inside the worktree. Both updates are needed: tools use
// CwdRef.Get() for path resolution, but exec'd children inherit the
// process cwd from os.Getwd().
func (t *EnterWorktreeTool) swapCwd(newDir string) error {
	if t.Cwd != nil {
		t.Cwd.Set(newDir)
	}
	if err := os.Chdir(newDir); err != nil {
		return fmt.Errorf("enter_worktree: chdir %s: %w", newDir, err)
	}
	return nil
}

// samePathBasic is a Clean-only compare for paths we know are already
// absolute. Avoids the symlink-resolution cost of filepath.EvalSymlinks
// in the hot tool-execute path.
func samePathBasic(a, b string) bool {
	return strings.TrimRight(strings.TrimSpace(a), "/") == strings.TrimRight(strings.TrimSpace(b), "/")
}
