// Package catalog is yottacode's source of truth for the set of cloud
// LLMs the wizard and TUI offer. The data lives in catalog.gen.json,
// regenerated by `go run ./cmd/yotta-models refresh` against each
// provider's list-models endpoint. Embedding the JSON keeps the binary
// self-contained and the user-facing flows offline-friendly.
//
// The schema is the union of fields any provider exposes — Anthropic
// and Gemini populate most of it, OpenAI's list endpoint is sparse so
// most fields are zero-valued for OpenAI rows. Capabilities use a
// tristate (*bool) so renderers can distinguish "not supported" from
// "not reported." Picker UI shows only known-true capabilities; a
// verbose details view shows the full tristate.
package catalog

import "time"

// Model is one entry in the catalog. Provider is always populated;
// every other field may be empty/zero when the source API doesn't
// surface that information. ID is the canonical model identifier the
// API will accept in subsequent calls.
type Model struct {
	ID            string       `json:"id"`
	DisplayName   string       `json:"display_name,omitempty"`
	Provider      string       `json:"provider"`
	ContextWindow int          `json:"context_window,omitempty"`
	MaxOutput     int          `json:"max_output,omitempty"`
	ReleasedAt    time.Time    `json:"released_at,omitempty"`
	Description   string       `json:"description,omitempty"`
	Capabilities  Capabilities `json:"capabilities,omitempty"`
}

// Capabilities is the small flag set we surface in the picker. *bool
// is intentional: nil means the provider didn't tell us, true means
// supported, false means explicitly not supported. Renderers should
// distinguish — chip rows show only true; details view shows all
// three states.
type Capabilities struct {
	Thinking          *bool `json:"thinking,omitempty"`
	Vision            *bool `json:"vision,omitempty"`
	PDF               *bool `json:"pdf,omitempty"`
	StructuredOutputs *bool `json:"structured_outputs,omitempty"`
	Tools             *bool `json:"tools,omitempty"`
}

// Label returns DisplayName when set, otherwise ID. Use this for any
// user-facing string; the picker should never render the bare ID when
// a friendlier name is available.
func (m Model) Label() string {
	if m.DisplayName != "" {
		return m.DisplayName
	}
	return m.ID
}
